
orgmode for Sublime Text 2
==========================

* About
  My shot on bringing Org-Mode {3} to Sublime Text 2 {4}. This project {1} is still in very early development. Nobody knows what will come next :). This won't be a simple copycat of the original one. I want to "port" useful things in a way that works best for Sublime Text 2. So there may be things that aren't in either version or just behave more or less differently.

* Features
  Here's a list of all the features implemented so far:

  - Context sensitive highlighting
    - Headlines
    - Pages
    - Breaks
    - Tacks
    - Checkboxes
    - Checkbox summaries
    - External links
    - Inter document links
  - Context sensitive actions
    - Toggle checkbox on pressing enter
    - Auto update of checkbox summary on toggle of checkboxes
    - Recalc number of children in checkbox summary on pressing enter
    - External link opener on pressing enter (e.g. [[http://www.google.de]])
      (currently only working on OSX)
    - Jumping between inter document links on pressing enter (e.g. {1})

* Installation

** Codebase
   Clone or copy the contents into a Packages/orgmode folder.

** Key bindings for interaction
   See "Key bindings for interaction" under "Attachments" below for details.

** Theme additions for proper syntax highlighting
   See "Theme additions for proper syntax highlighting" under "Attachments" below for details.

* Todo [1/10]
  - [ ] External link opener on pressing enter [1/3]
    - [X] on OSX
    - [ ] on Linux
    - [ ] on Windows
  - [X] Recalc number of children in checkbox summary on pressing enter.
  - [ ] When (un-)checking *all* checkboxes of siblings, toggle parent checkbox.
  - [ ] Either make highlight_code_remarks.py configurable thru view settings so that orgmode can control its regex patterns or fork/extend it to archive an equal goal.
  - [ ] Export into formatted text file
  - [ ] Automatic export after save into given format if mark found in org file.
  - [ ] Fix subsequent indents
  - [ ] Fix cursor position after filling checkbox summary on checkbox toggle
  - [ ] Tab trigger "[]" which extends into "[ ] " and updates the summary
  - [ ] Define special block/area in document where time logging can occur. If one changes the status (TODO, WORKING, DONE etc.) this will be written into the log. Ideas for format are welcome!

* Known Issues
  - When creating an empty checkbox summary and hitting an checkbox below the cursor will be placed a little bit to the left. Seems like the selection is being rebuilt incorrectly due to the added chars for the summary.
  - Subsequent indent of wrapped paragraphs don't respect stars, tacks and checkboxes.
  
* External links
  {1} Homepage [[https://bitbucket.org/theblacklion/sublime_orgmode/]]
  {2} Issue tracker [[https://bitbucket.org/theblacklion/sublime_orgmode/issues?status=new&status=open]]
  {3} Sublime Text 2 [[http://www.sublimetext.com/2]]
  {4} Org-Mode for Emacs [[http://orgmode.org/]]

* Attachments

** Key bindings for interaction
   Put the following into your key bindings file:

   [code]
   { "keys": ["enter"], "command": "orgmode_toggle_checkbox", "context":
     [
       { "key": "selector", "operator": "equal", "operand": "orgmode.checkbox" }
     ]
   },
   { "keys": ["enter"], "command": "orgmode_recalc_checkbox_summary", "context":
     [
       { "key": "selector", "operator": "equal", "operand":  "orgmode.checkbox.summary" }
     ]
   },
   {  "keys": ["enter"], "command": "orgmode_open_link", "con text":
      [
         { "key": "selector", "operator": "equal", "operand":  "orgmode.link" }
      ]
   },
   {  "keys": ["enter"], "command": "orgmode_cycle_internal_link", "context":
      [
         { "key": "selector", "operator": "equal", "operand":  "orgmode.link.internal" }
     ]
   }
   [/code]

** Theme additions for proper syntax highlighting
   Put the following into your theme file:

   [code]
   <dict>
       <key>name</key>
       <string>orgmode link</string>
       <key>scope</key>
       <string>orgmode.link</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FB9A4B</string>
         <key>fontStyle</key>
         <string>underline</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode page</string>
       <key>scope</key>
       <string>orgmode.page</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FFFFAA</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode break</string>
       <key>scope</key>
       <string>orgmode.break</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FFAAAA</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode headline</string>
       <key>scope</key>
       <string>orgmode.headline</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#9EFFFF</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode tack</string>
       <key>scope</key>
       <string>orgmode.tack</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FFFFAA</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode checkbox</string>
       <key>scope</key>
       <string>orgmode.checkbox</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FFFFAA</string>
      </dict>
   </dict>
   <dict>
       <key>name</key>
       <string>orgmode checkbox summary</string>
       <key>scope</key>
       <string>orgmode.checkbox.summary</string>
       <key>settings</key>
       <dict>
         <key>foreground</key>
         <string>#FFFFAA</string>
      </dict>
   </dict>
   [/code]
